import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className}  antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
